version: '3.9'
services:
  db:
    image: postgres:14.2
    restart: always
    env_file:
      - .env-example
    environment:
      - POSTGRES_PASSWORD=${database_password:-root}
      - POSTGRES_USER=${database_user:-root}
      - POSTGRES_DB=${database_name:-simple_message_board}
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    # ports:
    #   - 5432:5432
    networks:
      - local-networks
  app:
    build: simple-message-board/
    restart: always
    depends_on:
      - db
    env_file:
      - .env-example
    environment:
      - database_password=${database_password:-root}
      - database_name=${database_name:-simple_message_board}
      - database_user=${database_user:-root}
      - database_host=db
      - database_port=5432
    ports:
      - 8080:8080
    networks:
      - local-networks

  nginx-frontend-server:
    build:
      context: frontend-simple-message-board/
      args:
        - REACT_APP_API=/api/v1
    restart: always
    depends_on:
      - app
    env_file:
      - .env-example
    ports:
      - 80:80
    networks:
      - local-networks

networks:
  local-networks:
    driver: bridge

volumes:
  db_volume:
