version: '3.9'
services:
  db:
    image: postgres:14.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${database_password:-root}
      - POSTGRES_USER=${database_user:-root}
      - POSTGRES_DB=${database_name:-simple_message_board}
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
networks:
  local-networks:
    driver: bridge

volumes:
  db_volume:
